require "user.theme"
require "user.plugins"
require "user.which_key"
require "user.auto_commands"
require "user.globals"
require "user.options"
require "user.keymaps"
require "user.treesitter"
require "user.cmp"
require "user.nvim-ufo"
require "user.lsp"
require "user.dap"
require "user.nvim-tree"
require "user.lualine"
require "user.neogen"
require "user.formatter"
require "user.autosave"
require "user.toggleterm"
require "user.trouble"
require "user.goto_preview"
require "user.bqf"
require "user.telescope"
require "user.indent_blankline"


